#******************************************************************************
# Generated by Board2Make (https://github.com/luni64/Board2Make)
#
# Board              Teensy 3.2 / 3.1
# USB Type           Serial + MIDI
# CPU Speed          96 MHz (overclock)
# Optimize           Faster
# Keyboard Layout    US English
#
# Boards.txt          C:\Program Files (x86)\Arduino\hardware\teensy\avr\boards.txt 
#
# 29/04/2020 18:35
#******************************************************************************

TARGET_NAME := MIDI_controller

BOARD_ID    := TEENSY32
CORE_BASE   := C:\PROGRA~2\Arduino\hardware\teensy\avr\cores\teensy3
GCC_BASE    := C:\PROGRA~2\Arduino\hardware\tools\arm
UPL_PJRC_B  := C:\PROGRA~2\Arduino\hardware\tools
UPL_TYCMD_B := 

FLAGS_CPU   := -mthumb -mcpu=cortex-m4 -fsingle-precision-constant
FLAGS_OPT   := -O2
FLAGS_COM   := -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD
FLAGS_LSP   := 

FLAGS_CPP   := -fno-exceptions -fpermissive -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti
FLAGS_C     := 
FLAGS_S     := -x assembler-with-cpp
FLAGS_LD    := -Wl,--gc-sections,--relax,--defsym=__rtc_localtime=0

LIBS        := -larm_cortexM4l_math -lm
LD_SCRIPT   := mk20dx256.ld

DEFINES     := -D__MK20DX256__ -DTEENSYDUINO=151
DEFINES     += -DF_CPU=96000000 -DUSB_MIDI_SERIAL -DLAYOUT_US_ENGLISH

CPP_FLAGS   := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_CPP)
C_FLAGS     := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_C)
S_FLAGS     := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_S)
LD_FLAGS    := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_LSP) $(FLAGS_LD)
AR_FLAGS    := rcs

USR_SRC     := src
CORE_SRC    := $(CORE_BASE)

BIN         := bin
USR_BIN     := $(BIN)\src
CORE_BIN    := $(BIN)\core
CORE_LIB    := $(BIN)\core.a
TARGET_HEX  := $(BIN)\$(TARGET_NAME).hex
TARGET_ELF  := $(BIN)\$(TARGET_NAME).elf
TARGET_LST  := $(BIN)\$(TARGET_NAME).lst


#******************************************************************************
# BINARIES
#******************************************************************************
CC          := $(GCC_BASE)/bin/arm-none-eabi-gcc
CXX         := $(GCC_BASE)\bin\arm-none-eabi-g++
AR          := $(GCC_BASE)\bin\arm-none-eabi-gcc-ar
OBJCOPY     := $(GCC_BASE)\bin\arm-none-eabi-objcopy
SIZE        := $(GCC_BASE)\bin\arm-none-eabi-size
OBJDUMP     := $(GCC_BASE)\bin\arm-none-eabi-objdump
UPL_PJRC    := "$(UPL_PJRC_B)\teensy_post_compile" -test -file=$(TARGET_NAME) -path=$(BIN) -tools="$(UPL_PJRC_B)" -board=$(BOARD_ID) -reboot
UPL_TYCMD   := $(UPL_TYCMD_B)\tyCommanderC upload $(TARGET_HEX) --autostart

#******************************************************************************
# Source and Include Files
#******************************************************************************
# Recursively create list of source and object files in USR_SRC and CORE_SRC 
# and corresponding subdirectories. 
# The function rwildcard is taken from http://stackoverflow.com/a/12959694)

rwildcard =$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2))

#User Sources -----------------------------------------------------------------
USR_C_FILES    := $(call rwildcard,$(USR_SRC)/,*.c)
USR_CPP_FILES  := $(call rwildcard,$(USR_SRC)/,*.cpp)
USR_S_FILES    := $(call rwildcard,$(USR_SRC)/,*.S)
USR_OBJ        := $(USR_S_FILES:$(USR_SRC)/%.S=$(USR_BIN)/%.o) $(USR_C_FILES:$(USR_SRC)/%.c=$(USR_BIN)/%.o) $(USR_CPP_FILES:$(USR_SRC)/%.cpp=$(USR_BIN)/%.o) 

# Core library sources -------------------------------------------------------- 
CORE_CPP_FILES := $(call rwildcard,$(CORE_SRC)/,*.cpp)
CORE_C_FILES   := $(call rwildcard,$(CORE_SRC)/,*.c)
CORE_OBJ       := $(CORE_S_FILES:$(CORE_SRC)/%.S=$(CORE_BIN)/%.o) $(CORE_C_FILES:$(CORE_SRC)/%.c=$(CORE_BIN)/%.o) $(CORE_CPP_FILES:$(CORE_SRC)/%.cpp=$(CORE_BIN)/%.o) 

#$(info INFO: ${USR_OBJ})
#$(info INFO: ${CORE_OBJ})

INCLUDE        := -I.\$(USR_SRC) -I$(CORE_SRC)


#******************************************************************************
# Rules:
#******************************************************************************

.PHONY: all rebuild upload uploadTy clean cleanUser cleanCore

all:     $(TARGET_LST) $(TARGET_HEX)
rebuild: cleanUser all
clean:   cleanUser cleanCore

upload: $(TARGET_LST) $(TARGET_HEX)
	@$(UPL_PJRC)

uploadTy: $(TARGET_LST) $(TARGET_HEX)
	@$(UPL_TYCMD)

# Core library ----------------------------------------------------------------
$(CORE_BIN)/%.o: $(CORE_SRC)/%.S
	@echo [ASM] CORE $(notdir $<)
	@if not exist $(dir $@)  @mkdir "$(dir $@)"
	@"$(CC)" $(S_FLAGS) $(INCLUDE) -o $@ -c $< 

$(CORE_BIN)/%.o: $(CORE_SRC)/%.c
	@echo [CC]  CORE $(notdir $<)
	@if not exist $(dir $@)  @mkdir "$(dir $@)"
	@"$(CC)" $(C_FLAGS) $(INCLUDE) -o $@ -c $< 

$(CORE_BIN)/%.o: $(CORE_SRC)/%.cpp
	@echo [CPP] CORE $(notdir $<)
	@if not exist $(dir $@)  @mkdir "$(dir $@)"
	@"$(CXX)" $(CPP_FLAGS) $(INCLUDE) -o $@ -c $< 

$(CORE_LIB) : $(CORE_OBJ)
	@echo [AR]  $@
	@$(AR) $(AR_FLAGS) $@ $^
	@echo Teensy core built successfully &&echo.

# Handle user sources ---------------------------------------------------------
$(USR_BIN)/%.o: $(USR_SRC)/%.S
	@echo [ASM] $<
	@if not exist $(dir $@)  @mkdir "$(dir $@)"
	@"$(CC)" $(S_FLAGS) $(INCLUDE) -o $@ -c $<

$(USR_BIN)/%.o: $(USR_SRC)/%.c
	@echo [CC]  $(notdir $<)
	@if not exist $(dir $@)  @mkdir "$(dir $@)"
	@"$(CC)" $(C_FLAGS) $(INCLUDE) -o "$@" -c $<

$(USR_BIN)/%.o: $(USR_SRC)/%.cpp
	@echo [CPP] $<
	@if not exist $(dir $@)  @mkdir "$(dir $@)"
	@"$(CXX)" $(CPP_FLAGS) $(INCLUDE) -o "$@" -c $<

# Linking ---------------------------------------------------------------------
$(TARGET_ELF): $(CORE_LIB) $(USR_OBJ)
	@echo [LD]  $@
	@$(CC) $(LD_FLAGS) -T$(CORE_SRC)/$(LD_SCRIPT) -o "$@" $(USR_OBJ) $(CORE_LIB) $(LIBS)
	@echo User code built and linked to core lib &&echo.

%.lst: %.elf
	@echo [LST] $@
	@$(OBJDUMP) -d -S --demangle --no-show-raw-insn --syms "$<"  > "$@"
	@echo Listfile generated &&echo.

%.hex: %.elf
	@echo [HEX] $@
	@$(SIZE) "$<"
	@$(OBJCOPY) -O ihex -R.eeprom "$<" "$@"
	@echo Sucessfully built project &&echo.

# Cleaning --------------------------------------------------------------------
cleanUser:
	@echo Cleaning user binaries...
	@if exist $(USR_BIN) rd /s/q "$(USR_BIN)"

	@if exist $(TARGET_HEX) del  $(TARGET_HEX)
	@if exist $(TARGET_ELF) del  $(TARGET_ELF)
	@if exist $(TARGET_LST) del  $(TARGET_LST)

cleanCore:
	@echo Cleaning core binaries...
	@if exist $(CORE_BIN) rd /s/q "$(CORE_BIN)"
	@if exist $(CORE_LIB) del  "$(CORE_LIB)"

# compiler generated dependency info ------------------------------------------
-include $(CORE_OBJ:.o=.d)
-include $(USR_OBJ:.o=.d)
